// <auto-generated />
using CRUD__PPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD__PPI.Migrations
{
    [DbContext(typeof(OrdenesCuentaBDContext))]
    [Migration("20240805170624_actives")]
    partial class actives
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD__PPI.Models.Active", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoActivo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Actives");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Apple",
                            precioUnitario = 177.97m,
                            ticker = "AAPL",
                            tipoActivo = 1
                        },
                        new
                        {
                            id = 2,
                            nombre = "Alphabet Inc",
                            precioUnitario = 138.21m,
                            ticker = "GOOGL",
                            tipoActivo = 1
                        },
                        new
                        {
                            id = 3,
                            nombre = "Microsoft",
                            precioUnitario = 329.04m,
                            ticker = "MSFT",
                            tipoActivo = 1
                        },
                        new
                        {
                            id = 4,
                            nombre = "Coca Cola",
                            precioUnitario = 58.3m,
                            ticker = "KO",
                            tipoActivo = 1
                        },
                        new
                        {
                            id = 5,
                            nombre = "Walmart",
                            precioUnitario = 163.42m,
                            ticker = "WMT",
                            tipoActivo = 1
                        },
                        new
                        {
                            id = 6,
                            nombre = "BONOS ARGENTINA USD 2030 L.A",
                            precioUnitario = 307.4m,
                            ticker = "AL30",
                            tipoActivo = 2
                        },
                        new
                        {
                            id = 7,
                            nombre = "Bonos Globales Argentina USD Step Up 2030",
                            precioUnitario = 336.1m,
                            ticker = "GD30",
                            tipoActivo = 2
                        },
                        new
                        {
                            id = 8,
                            nombre = "Delta Pesos Clase A",
                            precioUnitario = 0.0181m,
                            ticker = "Delta.Pesos",
                            tipoActivo = 3
                        },
                        new
                        {
                            id = 9,
                            nombre = "Fima Premium Clase A",
                            precioUnitario = 0.0317m,
                            ticker = "Fima.Premium",
                            tipoActivo = 3
                        });
                });

            modelBuilder.Entity("CRUD__PPI.Models.OrdenesCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Accaunt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quanity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrdenesCuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
